# Generated by Django 3.0.7 on 2020-07-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Article categories',
            },
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts request',
            },
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_first_name', models.CharField(max_length=20)),
                ('design_last_name', models.CharField(max_length=20)),
                ('design_email', models.EmailField(max_length=30)),
                ('design_phone_number', models.CharField(max_length=12)),
                ('design_text', models.TextField(max_length=500)),
                ('design_date', models.DateField(auto_now_add=True, null=True)),
                ('design_firm', models.CharField(blank=True, max_length=50)),
                ('design_website', models.CharField(blank=True, max_length=50)),
                ('design_website_type', models.CharField(choices=[('0', 'Pasirinkite svetainės tipą'), ('100', 'Portfolio'), ('300', 'Commerce'), ('800', 'Custom')], default=('100', 'Portfolio'), max_length=20)),
                ('design_website_pages', models.CharField(choices=[('0', 'Preliminarus puslapių skaičius'), ('50', 'Preliminarus puslapių skaičius - 5'), ('100', 'Preliminarus puslapių skaičius - 6'), ('150', 'Preliminarus puslapių skaičius - 7')], default=('50', 'Preliminarus puslapių skaičius - 5'), max_length=20)),
                ('design_locked_paitn', models.BooleanField(default=True)),
                ('design_locked_kait', models.BooleanField(default=True)),
                ('design_locked_sia', models.BooleanField(default=True)),
                ('design_locked_ssk', models.BooleanField(default=True)),
                ('design_locked_dke', models.BooleanField(default=True)),
                ('design_locked_dmie', models.BooleanField(default=True)),
                ('design_locked_dpe', models.BooleanField(default=True)),
                ('design_locked_pk', models.BooleanField(default=True)),
                ('design_testing_cycle', models.CharField(choices=[('0', 'Testavimo ciklai'), ('100', 'A Ciklas'), ('200', 'B Ciklas'), ('300', 'C Ciklas')], default=('100', 'A Ciklas'), max_length=20)),
                ('design_optional_tidt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EshopRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eshop_first_name', models.CharField(max_length=20)),
                ('eshop_last_name', models.CharField(max_length=20)),
                ('eshop_email', models.EmailField(max_length=30)),
                ('eshop_phone_number', models.CharField(max_length=12)),
                ('eshop_text', models.TextField(max_length=500)),
                ('eshop_date', models.DateField(auto_now_add=True, null=True)),
                ('eshop_firm', models.CharField(blank=True, max_length=50)),
                ('eshop_website', models.CharField(blank=True, max_length=50)),
                ('eshop_locked_uisd', models.BooleanField(default=True)),
                ('eshop_tvs_choices', models.CharField(choices=[('0', 'Pasirinkite turinio valdymo sistemą'), ('100', 'A'), ('150', 'B'), ('200', 'C')], default=('100', 'A'), max_length=20)),
                ('eshop_locked_tvs', models.BooleanField(default=True)),
                ('eshop_locked_sti', models.BooleanField(default=True)),
                ('eshop_locked_iz', models.BooleanField(default=True)),
                ('eshop_locked_uz', models.BooleanField(default=True)),
                ('eshop_locked_seo', models.BooleanField(default=True)),
                ('eshop_locked_gai', models.BooleanField(default=True)),
                ('eshop_locked_fpi', models.BooleanField(default=True)),
                ('eshop_locked_pk', models.BooleanField(default=True)),
                ('eshop_locked_pf', models.BooleanField(default=True)),
                ('eshop_optional_d', models.BooleanField(default=False)),
                ('eshop_optional_lc', models.BooleanField(default=False)),
                ('eshop_optional_st', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=40)),
                ('project_url', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=25)),
                ('intro_title', models.CharField(max_length=30)),
                ('intro_text', models.CharField(max_length=50)),
                ('intro_image', models.ImageField(upload_to='projects_covers')),
                ('date', models.DateField(auto_now_add=True)),
                ('inside_title', models.CharField(max_length=80)),
                ('inside_text', models.CharField(max_length=200)),
                ('a_1', models.CharField(max_length=100)),
                ('a_2', models.CharField(max_length=100)),
                ('a_3', models.CharField(max_length=100)),
                ('a_4', models.CharField(max_length=100)),
                ('tech_stack', models.ImageField(upload_to='')),
                ('project_images', models.ImageField(upload_to='')),
                ('write_up', models.CharField(max_length=300)),
                ('owner_name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='Projects_logos')),
            ],
        ),
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('web_locked_uisd', models.BooleanField(default=True)),
                ('web_locked_tvs', models.BooleanField(default=True)),
                ('web_locked_sti', models.BooleanField(default=True)),
                ('web_locked_iz', models.BooleanField(default=True)),
                ('web_locked_uz', models.BooleanField(default=True)),
                ('web_locked_seo', models.BooleanField(default=True)),
                ('web_locked_gai', models.BooleanField(default=True)),
                ('web_pages_select', models.CharField(choices=[('0', 'Preliminarus puslapių skaičius'), ('50', 'Preliminarus puslapių skaičius - 5'), ('100', 'Preliminarus puslapių skaičius - 6'), ('150', 'Preliminarus puslapių skaičius - 7')], default=('50', 'Preliminarus puslapių skaičius - 5'), max_length=20)),
                ('web_optional_fpi', models.BooleanField(default=False)),
                ('web_optional_pk', models.BooleanField(default=False)),
                ('web_optional_pf', models.BooleanField(default=False)),
                ('web_optional_d', models.BooleanField(default=False)),
                ('web_optional_lc', models.BooleanField(default=False)),
                ('web_optional_st', models.BooleanField(default=False)),
                ('web_firm', models.CharField(blank=True, max_length=50)),
                ('web_website', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20, unique=True)),
                ('cover', models.ImageField(upload_to='article_covers')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ArticleCategory')),
            ],
        ),
    ]
