# Generated by Django 3.0.7 on 2020-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='inside_intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
    ]
