# Generated by Django 3.0.7 on 2020-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200708_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_images',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='write_up',
            field=models.TextField(max_length=300),
        ),
    ]
